wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 80:80
  # optional, files are located on the host instead of in the container
  volumes:
    - ~/wordpress/wp_html:/var/www/html
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: examplepass
  # optional, files are located on the host instead of in the container
  volumes:
    - ~/wordpress_db:/var/lib/mysql
# optional, comunity phpmyadmin image used, above wordpress/db setup can work without it
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: examplepass
