---
# Digital Ocean documentation
# https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-ubuntu-16-04
- name: Install python3 related pkgs
  become: true
  apt: name={{ item }} state=present
  with_items:
    - python3-pip # https://pypi.python.org/pypi
    - python3-venv
    - idle3
    - ipython3
    - libssl-dev 
    - libffi-dev
    - python3-tk
