---
- hosts: apache
  become: True
  vars:
    http_port: 80
    domain: example.com

  tasks:
    - name: install apache2
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - apache2
        - git

    - name: enable mod_rewrite
      apache2_module: >
        name=rewrite
        state=present
      notify: restart apache2

    - name: apache2 listen on port defined via vars
      lineinfile: >
        dest=/etc/apache2/ports.conf
        regexp="^Listen"
        line="Listen {{ http_port }}"
        state=present
      notify: restart apache2

    - name: apache2 virtualhost on port defined via vars
      lineinfile: >
        dest=/etc/apache2/sites-available/000-default.conf
        regexp="^<VirtualHost \*:80>"
        line="<VirtualHost *:{{ http_port }}>" 
        state=present
      notify: restart apache2

    - name: create virtual host file
      template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

    - name: a2ensite {{ domain }}
      command: a2ensite {{ domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ domain }}.conf
      notify:
      - restart apache2

    - name: clone basic html template
      git: >
        repo=https://github.com/do-community/ansible-apache-tutorial.git 
        dest=/var/www/example.com 
        update=no


  handlers:
    - name: restart apache2
      service: >
        name=apache2
        state=restarted
